name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm install
      - name: Build with environment variables
        run: npm run generate
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          AIRKOREA_API_KEY: ${{ secrets.AIRKOREA_API_KEY }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: "weatheralarm-155bf"
          channelId: "live"
